language: python
dist: trusty
python:
- '3.5'
install:
- pip install -r requirements_dev.txt
env:
- FBID=1198658993509311 PAGE_ACCESS_TOKEN=EAAYiKvTIihQBAGp5T9M8EDE4wWuu01v39bEjw2i82atSHUTzCcqqnQMsEJrLsZAbU9ZBIQZAkO9RZCmaesalGBtcjX8tuFq8z2SYiT6VxdH1IWf2l17kegoQ0ZAttMnsQZAMMZBUPp3OtCOvQWKGuVzKrFEv1qdsQXsYYBHgFqaHAZDZD
script:
- python -m unittest tests.test
- flake8 fbbotw tests
